### ISSUE TITLE
Use of Uninitialized Variable in `get_pours`

### ISSUE THREAD

**Issue by jsr5194** [jpecsi/kegwatch#1]
https://github.com/jpecsi/kegwatch/blob/6693fdec31b371a5275a98f1e4be996218c8466c/server/api/api.py#L281

Without an `else` case or a pre-defined `results` variable you are trying to return something that doesn't exist yet. ~~Hitting the url below causes subsequent requests to hang~~. Looks like that hang may have been caused by a different issue

`http://KEGWATCH_SERVER_IP:25518/pours/list/foo/bar`

**Comment by jpecsi** [comment]
Resolved in version 0.2
