### ISSUE TITLE
Unreachable Code - exception on the json conversion

### ISSUE THREAD

**Issue by jsr5194** [jpecsi/kegwatch#11]
https://github.com/jpecsi/kegwatch/blob/75a889a473b685770b245c5bb087212fa4691b55/server/api/api.py#L391

Since you're taking data in via a GET request the `id` param isn't coming in as json. Probably want to switch this to a POST request so json data can be passed

Request:

```
GET /pours/list/tap?id=1 HTTP/1.1
Host: localhost:25518
<snipped>

```

Response:

```
{"response": "415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'."}
```

**Comment by jpecsi** [comment]
Kept it as GET, added the 'id' for tap or keg as input on the URL, doing validation within the method
