### ISSUE TITLE
Likely typo in db query in`post_new_keg`

### ISSUE THREAD

**Issue by jsr5194** [jpecsi/kegwatch#4]
https://github.com/jpecsi/kegwatch/blob/6693fdec31b371a5275a98f1e4be996218c8466c/server/api/api.py#L154

looks like you have `keg_size` twice here - is that intentional?

**Comment by jpecsi** [comment]
This is intentional, when adding a new keg (in most situations) it will be full. For the edge cases where you tap a partially consumed keg, the user can use the update function to modify keg details
